# Generated by Django 4.2.4 on 2023-08-16 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='lojas',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lojas',
            name='status_concluida',
            field=models.CharField(choices=[('sim', 'Concluida'), ('nao', 'Nao Concluida')], default='nao', max_length=100),
        ),
        migrations.CreateModel(
            name='Regionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('loja_atual', models.CharField(max_length=100)),
                ('porcentagem_conclusao', models.PositiveIntegerField()),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional', to='dashboard.equipes')),
            ],
        ),
        migrations.AddField(
            model_name='lojas',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='dashboard.equipes'),
        ),
        migrations.AddField(
            model_name='lojas',
            name='regiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.regionais'),
        ),
    ]
