# Generated by Django 4.2.4 on 2023-08-16 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_equipes_alter_lojas_nome_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipes',
            new_name='Equipe',
        ),
        migrations.RenameModel(
            old_name='Lojas',
            new_name='Loja',
        ),
        migrations.RenameModel(
            old_name='Regionais',
            new_name='Regionai',
        ),
    ]
