# Generated by Django 4.2.4 on 2023-08-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_equipes_equipe_rename_lojas_loja_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regionai',
            new_name='Regional',
        ),
    ]
