# Generated by Django 4.2.4 on 2023-08-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_regionai_regional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipe',
            options={'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
        migrations.AlterModelOptions(
            name='loja',
            options={'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.AlterModelOptions(
            name='regional',
            options={'verbose_name': 'Regional', 'verbose_name_plural': 'Regionais'},
        ),
    ]
