# Generated by Django 4.2.4 on 2023-08-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_suporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.regional'),
        ),
    ]
