# Generated by Django 4.2.4 on 2023-08-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_suporte_regional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regional',
            name='loja_atual',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
