# Generated by Django 4.2.4 on 2023-08-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_regional_loja_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regional',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional', to='dashboard.equipe'),
        ),
    ]
