# Generated by Django 4.2.4 on 2023-08-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_dashboard_equipe_dashboard_loja_dashboard_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
    ]
