# Generated by Django 4.2.4 on 2023-08-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_dashboard_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suporte',
            name='regional',
        ),
        migrations.AddField(
            model_name='suporte',
            name='regional',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.regional'),
        ),
    ]
