# Generated by Django 4.2.4 on 2023-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_suporte_regional_suporte_regional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='regional',
            name='dashboard',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='equipes',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.equipe'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='lojas',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.loja'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='regionais',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.regional'),
        ),
    ]
