# Generated by Django 4.2.4 on 2023-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_dashboard_equipes_alter_dashboard_lojas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='regional',
            field=models.ManyToManyField(blank=True, to='dashboard.regional'),
        ),
    ]
