# Generated by Django 4.2.4 on 2023-08-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_suporte_regional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
