# Generated by Django 4.2.4 on 2023-08-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_loja_status_concluida_loja_concluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='equipes',
            field=models.ManyToManyField(blank=True, to='dashboard.equipe'),
        ),
    ]
