# Generated by Django 4.2.4 on 2023-08-18 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_dashboard_equipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.equipe'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='regiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='dashboard.regional'),
        ),
    ]
