# Generated by Django 4.2.4 on 2023-08-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_loja_equipe_alter_loja_regiao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='equipes',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='lojas',
        ),
    ]
