# Generated by Django 4.2.4 on 2023-08-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_suporte_regiao_ativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suporte',
            name='regional',
        ),
        migrations.AddField(
            model_name='suporte',
            name='regiao_ativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suporte', to='dashboard.regional'),
        ),
    ]
